### ISSUE TITLE
Encode output according to the environment

### ISSUE THREAD

**Issue by JulienPalard** [makamaka/JSON-PP#16]
Let's just start by sticking some vocabulary so we speak the same language:

 - JSON is plain ASCII. Non ASCII characters are escaped as a sequence of ASCII characters as unicode codepoints like \uxxxx.
 - There is no such thing as JSON-utf8 or JSON-latin1, JSON is a sequence of ASCII characters http://json.org/
 - I'm not speaking of STDIN decoding, it's ASCII, nobody cares.
 - I'm speaking of STDOUT encoding, any program have to encode according to how the terminal emulator display bytes sequences so someone with a latin-1 terminal will receive latin-1 encoded characters, and someone with an UTF-8 terminal will receive UTF-8 encoded characters.
 - A user should not have to explicitly tell a program its current terminal encoding by giving a command-line parameter. 

Now the problem: When I feed unicode codepoints to `json_pp` on an UTF-8 (explicitly configured) terminal I'm getting latin-1 encoded characters.

```
$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.utf8"
LC_NUMERIC="en_US.utf8"
LC_TIME="en_US.utf8"
LC_COLLATE="en_US.utf8"
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=en_US.utf8
$ echo '["\u00e0"]' | json_pp
[
   "�"
]
$ echo '["\u00e0"]' | json_pp | hexdump -C
00000000  5b 0a 20 20 20 22 e0 22  0a 5d 0a                 |[.   ".".].|
0000000b
```

I expect json_pp to be environment aware, and to encode STDOUT according to this. It should check for some environment variables, first, `LC_ALL` that have precedence over `LC_CTYPE`, then LANG and LANGUAGE may be checked. LANG and LANGUAGES are not directly linked to encoding, but more to languages. Yet at this step we're searching for a hint about the user (terminal) encoding, and if the user explicitly set "LANGUAGE=en_DK.iso885915", we don't care about the language, but clearly, he uses iso885915 as an encodage: Bingo we got it.

As a non-perl developper I think I'm going a little too far here and that perl should probably expose this to you so you don't have to do all this stuff of deducing the actual encoding to use on STDOUT, I let that research to you.

What I expect:
```
$ echo '["\u00e0"]' | LC_ALL=en_US.utf8 json_pp | hexdump -C
00000000  5b 0a 20 20 20 22 c3 a0  22 0a 5d 0a              |[.   "..".].|
0000000c
$ echo '["\u00e0"]' | LC_ALL=en_US.iso885915 json_pp | hexdump -C
00000000  5b 0a 20 20 20 22 e0 22  0a 5d 0a                 |[.   ".".].|
0000000b
```

Note that I'm using LC_ALL, which should have precedence over all others (see `man 7 locale`).

**Comment by leonerd** [comment]
As a quick note on implementation: It would be easy to detect this based on the `${^UTF8LOCALE}` variable. In fact, the code could probably do a simple

    push @json_opts, "utf8" if ${^UTF8LOCALE};

Though it might further want to first check that the user hadn't already asked for `ascii` or the ill-advised `latin1` first.

**Comment by leonerd** [comment]
push @json_opts, "utf8" if ${^UTF8LOCALE} and not grep { $_ eq "ascii" or $_ eq "latin1" } @json_opts

**Comment by JulienPalard** [comment]
However, there's not just latin1, ascii, and utf8:
```
$ iconv -l | wc -l
1173
```

More like ~1000 of them.

**Comment by haarg** [comment]
The proper thing to do to fix this would be to load Encode::Locale and apply the locale encoding to STDOUT.

I'm not sure what you mean with your first two bullet points.  JSON is composed of unicode characters, not just ASCII.  It can be encoded either as UTF-8, UTF-16, or UTF-32.  It is of course also possible to limit it to the ASCII range by escaping all of the characters using \uXXXX sequences.

**Comment by JulienPalard** [comment]
> JSON is composed of unicode characters,

You're right, I misread the doc, I though JSON was only ASCII characters and all non-ASCII ones were always encoded using the "\uxxxx" notation, my bad.

So I'm wrong for the STDIN part but this changes almost nothing:

STDOUT encoding is still available from the locale, but the STDIN encoding can't be guessed, so we should probably use the same as STDOUT encoding, being sometimes wrong if STDIN is a file encoded in another encoding...

In this case the user should better use `iconv` to provide the same encoding as the local one to `json_pp` ? I mean, that's not the tool responsibility to guess the encoding of an unknown input, nor to convert it. (there is no --from utf32 in `grep`, `sed`, `awk`, etc...)

**Comment by haarg** [comment]
The input on STDIN is supposed to be JSON, so it should be one of the UTF encodings, as the spec requires.  Which one could be automatically detected easily.  Using the same encoding as STDOUT would be a mistake.

**Comment by JulienPalard** [comment]
I agree on "Using the same encoding as STDOUT would be a mistake".

Where on the documentation did you find that JSON should be encoded in "one of the UTF encodings" ? I never read that.

**Comment by haarg** [comment]
Both [RFC-4627](https://tools.ietf.org/html/rfc4627#page-5) and [RFC-7159](https://tools.ietf.org/html/rfc7159#section-8.1) document the character encoding of JSON.

**Comment by charsbar** [comment]
> A user should not have to explicitly tell a program its current terminal encoding by giving a command-line parameter.

This assumption is completely wrong when the output of json_pp is passed to another program. It also doesn't work when the terminal encoding is not unicode compatible (say, an Asian encoding).
If you want a DWIW-encoded JSON, you should tell json_pp so, and you should also use other proper tool (piconv or nkf or whatever) to convert the encoding.
