### ISSUE TITLE
2.9? version number after 2.27201 confusion

### ISSUE THREAD

**Issue by dansut** [makamaka/JSON-PP#33]
I'm having a bit of a dependency issue with the fact that version 2.93 looks to be older than 2.27201 (93 < 27201) - the issue occurs for for me while rebuilding RPMs under EL6 but I imagine it is a problem throughout perl installs, it seems Fedora have resolved by ignoring your numbering and creating 2.27400 packages...

If you don't like the 5 digit minor version numbers a leap to major version 3 would seem to be the simplest way to fix this dependency issue.

**Comment by charsbar** [comment]
Thanks. I changed the version format to use 5 digit minor version number again (until 3.xx).
