### ISSUE TITLE
Stringification behaviour change breaks UR and PGObject-Type-JSON tests

### ISSUE THREAD

**Issue by ntyni** [makamaka/JSON-PP#39]
While testing the Perl 5.28.0 release candidates (which contain JSON-PP  2.97001) we have noticed a behaviour change in JSON::PP that broke some tests in UR and PGObject-Type-JSON. 

- https://bugs.debian.org/901082

- https://bugs.debian.org/901085

I was able to reduce the change to

`perl -MJSON::PP -le '$p=123; "". $p; print JSON::PP->new->allow_nonref->encode($p)'`

which outputs 123 (a number) on current JSON-PP, and "123" (a string) on older ones.

This bisects to 87bd6a49bacc3a2634cbb1dd0ce9cc75675bb524 and deviates from what JSON::XS does FWIW. Do you think this is something that should be fixed in JSON-PP, or do the other test suites just need to adapt?

I don't know why the test suite failures we're seeing don't seem to be visible on CPAN tester reports. Maybe those have JSON::XS pulled in somehow so it hides the issues?

Many thanks for your work on JSON-PP!

**Comment by charsbar** [comment]
I'm sorry I haven't replied this issue for so long. Just for your information, now you can use an environmental variable PERL_JSON_PP_USE_B to restore old behavior that used B when necessary (since version 3.99_01 released in December 2018).
