### ISSUE TITLE
numeric zeroes are decoded as a string 

### ISSUE THREAD

**Issue by bchan12** [makamaka/JSON-PP#41]
Hi I am trying to use the "allow_bignum" feature so I can handle Big Int, however, with allow_bignum enabled, numerical zeroes (the values of "status" in the following example) in the incoming json are being decoded as strings. This does not occur without enabling allow_bignum. Furthermore, the usual 'trick' of *= 1 or += 0 does not rescue them back as numerical values. Dumping out the zero with Devel::Peek seems to show that allow_bignum has turn the zero into an object too? But I am not educated enough to fully grasp what all that stuff means. Sorry. 

Any help is greatly appreciated! 

Output of test code: 
`IN:
 {"test":-1,"big int":12345678901234567890,"other":1,"status":0}`
`OUT:
 {"status":"0","other":1,"test":-1,"big int":12345678901234567890}
`

Test code: 
`use JSON;

my $json=new JSON;
   $json->allow_bignum;
my $bigint  = $json->decode('12345678901234567890');
my $jsonstr = $json->encode({"status" => 0,"big int"=>$bigint,"other"=>1,"test"=>-1});

print "IN:\n $jsonstr\n";

my $ref = $json->decode($jsonstr);

my $status = $ref->{status};

print "OUT:\n ",$json->encode($ref),"\n";
`

**Comment by charsbar** [comment]
@bchan12 , it's most likely you are using JSON::XS (that doesn't support allow_bignum) behind JSON. Replace ```(use|new) JSON``` with ```JSON::PP```, then you should get what you need.

**Comment by charsbar** [comment]
Ah, no. Sorry that seems not the case. I don't reproduce the issue with the latest JSON::PP, so try the latest version.

**Comment by charsbar** [comment]
Closing.
