### ISSUE TITLE
On JSON:PP mention how to pretty print json from json just like json_pp does

### ISSUE THREAD

**Issue by jidanni** [makamaka/JSON-PP#44]
On man json_pp it says:

> The default input format is json and the default output format is json with pretty option.

OK, on the highly related JSON::PP man page, wouldn't it be nice in
passing mention, to mention how to achieve the same output of json_pp?

>      ..... ........ ......... ...... # Makes exactly same output as "json_pp < file"

Indeed, on the JSON::PP there is no mention of how to pretty print json
directly like that: apparently one is supposed to convert json into a perl_scalar
then convert it back to pretty printed json.

**Comment by charsbar** [comment]
See also section in the pod has a mention about json_pp command line utility for quick experiments. I think that's enough.
