### ISSUE TITLE
incr_parse dies on partial strings

### ISSUE THREAD

**Issue by Sec42** [makamaka/JSON-PP#45]
Calling `incr_parse` with an unterminated string causes JSON:PP to die.

```
 PERL_JSON_BACKEND=JSON::PP perl -MData::Dump=dump -MJSON -E 'my $json = JSON->new;@foo=$json->incr_parse(q!{"check_result!); $bar=$json->incr_parse(q!" : "ok"}!); dump $bar'
```

Output: `unexpected end of string while parsing JSON string, at character offset 14 (before "(end of string)") at -e line 1.`

It works fine with JSON::XS
```
 PERL_JSON_BACKEND=JSON::XS perl -MData::Dump=dump -MJSON -E 'my $json = JSON->new;@foo=$json->incr_parse(q!{"check_result!); $bar=$json->incr_parse(q!" : "ok"}!); dump $bar
```
Output: `{ check_result => "ok" }`

Thanks to haj, see: https://www.perlmonks.org/?node_id=1229969

**Comment by charsbar** [comment]
@Sec42  I assume you are using an older version of JSON::PP (probably the one bundled with perl). Please install a recent version (2.92 and higher), and it should work. If not, please let me know the version of JSON::PP, perl, and OS you are using.

**Comment by Sec42** [comment]
The host in question is Centos 7 so I'm basically stuck at:

perl.x86_64                              4:5.16.3-293.el7    @centos7-x86_64    
perl-JSON.noarch                         2.59-2.el7          @centos7-x86_64    
perl-JSON-PP.noarch                      2.27202-2.el7       @centos7-x86_64    

I already installed JSON-XS instead which works, and I'll leave it at that.
