### ISSUE TITLE
Encoding error

### ISSUE THREAD

**Issue by JulienPalard** [makamaka/JSON-PP#47]
I'm having the following issue:
```
$ echo '["é"]' | json_pp
[
   "Ã©"
]
```

I know that encoding problems are hard (https://github.com/makamaka/JSON-PP/issues/16), sorry for this issue.

It looks like `json_pp` treated my input as being `latin-1` while my input was UTF-8, a bit like this:
```
$ echo '["é"]' | iconv -f latin1 -t utf8
["Ã©"]
```

My input being:
```
$ echo '["é"]' | hexdump -C
00000000  5b 22 c3 a9 22 5d 0a                              |[".."].|
00000007
```
`\xc3\xa9` being the UTF-8 encoding for é:
```
$ unicode é
U+00E9 LATIN SMALL LETTER E WITH ACUTE
UTF-8: c3 a9 UTF-16BE: 00e9 Decimal: &#233; Octal: \0351
é (É)
Uppercase: 00C9
Category: Ll (Letter, Lowercase); East Asian width: A (ambiguous)
Unicode block: 0080..00FF; Latin-1 Supplement
Bidi: L (Left-to-Right)

Decomposition: 0065 0301


```

According to https://tools.ietf.org/html/rfc7159#section-8.1:
```
JSON text SHALL be encoded in UTF-8, UTF-16, or UTF-32.  The default encoding is UTF-8
```

So assuming it's latin1 looks wrong to me.

My locales configuration does not advertise latin1, but UTF8:
```
$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.utf8"
LC_NUMERIC="en_US.utf8"
LC_TIME="en_US.utf8"
LC_COLLATE="en_US.utf8"
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=en_US.utf8
```

So I don't think picking latin1 is a safe bet here, I think json_pp should move a tad towards thinking the input is UTF-8.

It works with `-json_opt utf8`, maybe it should be the default? What is the current heuristic to determine input encoding?

**Comment by charsbar** [comment]
Thank you for the report. Fixed by https://github.com/makamaka/JSON-PP/commit/2bba2447050e9395d5b2f0c83305fca8325f2294 .
