### ISSUE TITLE
RFE: Remove utf8::upgrade & utf8::downgrade

### ISSUE THREAD

**Issue by FGasper** [makamaka/JSON-PP#58]
Since this is a pure Perl module there should be no need to care about Perl’s internals, which is what upgrade() achieves. downgrade() does at least usefully confirm that no >255 code point is part of the string, but upgrade() seems rather pointless.

In fact, the upgrade() will often cause “Unicode Bug” problems like this:
```
>  perl -MJSON::PP -MData::Dumper -e'exec echo => decode_json(encode_json(["é"]))->[0]'
Ã©
```

**Comment by charsbar** [comment]
Closing as #59 is merged.
