### ISSUE TITLE
New test file name is too long to ship with perl core

### ISSUE THREAD

**Issue by khwilliamson** [makamaka/JSON-PP#65]
I took the newly merged pul requests to try out on an EBCDIC box to make sure they worked in that exotic situation.  They did!  However, the file rt_122270_is_bool_for_obsolete_xs_boolean.t needs to have its name shortened.  There is a test in the perl core it is failing, which restricts file name lengths to 39 characters.  Someone wrote this because some system had that restriction.  Perhaps those systems are gone, so the test is obsolete; I don't know, but it seems like the path of least effort is to just shorten the file name; otherwise there will be complications when the next release of this module is attempted to be imported and shipped with Perl core.

**Comment by charsbar** [comment]
I made the filename a little shorter. Thanks.
