### ISSUE TITLE
perl 5.6 support broken

### ISSUE THREAD

**Issue by haarg** [makamaka/JSON-PP#83]
Since version 4.07, JSON-PP fails its tests on perl 5.6. There are a few issues:

  * JSON::PP is now using the function `utf8::unicode_to_native`, which is not provided by perl 5.6 or JSON::PP::Compat5006.
  * The `t/119_incr_parse_utf8.t` file uses Encode, which is not available on perl 5.6. This is easy enough to solve by using `utf8::encode`. 
  * Incremental parsing seems broken on UTF-8 content. This also causes the `t/119_incr_parse_utf8.t` test to fail.

There are a few possible solutions to these. Fixing incremental parsing does not look trivial. Possibly it could be allowed to fail on UTF-8 content on perl 5.6, and the tests could skip. Fixing the incremental parsing test to avoid Encode is easy. Alternatively, the tests could just be allowed to fail on perl 5.6, like they do on perl 5.005. Patching JSON::PP::Compat5006 to provide the `utf8::unicode_to_native` function is probably viable although I'm not sure how to test on EBCDIC systems.

The other option is dropping perl 5.6 support, which would allow simplifying a number of parts of the code.

Let me know what you think the best approach to this is. I'm willing to work on fixing it.

**Comment by charsbar** [comment]
makamaka, the original author, agreed to drop 5.5/5.6 support :)

**Comment by haarg** [comment]
Fixed by #84
