### ISSUE TITLE
JSON:PP decode failure on input accepted by json_pp utility 

### ISSUE THREAD

**Issue by ahmogit** [makamaka/JSON-PP#85]
Greetings,

Attached are two files, **minex_perlscript.txt** and **minex_input.txt**.  The comments in the Perl script describe the issue.

Perl version is 5.36.0, running on Arch linux.

json_pp -v reports version 4.07.

Thank you.

[minex_input.txt](https://github.com/makamaka/JSON-PP/files/10322672/minex_input.txt)
[minex_perlscript.txt](https://github.com/makamaka/JSON-PP/files/10322673/minex_perlscript.txt)

**Comment by charsbar** [comment]
You are encountering the error because `$str = <>;` only reads the first line of the JSON. Add `local $/;` before reading as json_pp does (https://github.com/makamaka/JSON-PP/blob/master/bin/json_pp#L95-L99).

**Comment by ahmogit** [comment]
Arggh.... Thanks, and apologies for the noise.
