### ISSUE TITLE
JSON5: double-quotes inside a string with single-quote delimiters

### ISSUE THREAD

**Issue by jforget** [makamaka/JSON-PP#90]
Context
=======

The V5 version of JSON provides several extensions to the JSON syntax:

* allow comments,

* allow trailing commas in arrays and objects,

* more permissive syntax for numbers,

* use single quotes as string delimiters,

* or even omit them for some keys in key-value pairs

and other additions. See [https://json5.org/](https://json5.org/).

The JSON::PP module supports some extensions by calling the proper methods.
Thus, this program runs fine:

```
# -*-*-*-*-*- begin
use JSON::PP;

my $song = <<'EOF';
{ title : 'Hello Goodbye',
  verse : [ 'You say yes, I say no',
            'You say stop, I say go, go, go'
          ]
}
EOF
my $json = JSON::PP->new->allow_singlequote->allow_barekey;
my $result = $json->decode($song);
# -*-*-*-*-*- end
```

Bug
===

Yet, if a single-quote-delimited string contains a double-quote,
the parsing fails:

```
# -*-*-*-*-*- begin
use JSON::PP;

my $song = <<'EOF';
{ 'title' : 'Hello Goodbye',
  'verse' : [ 'You say "yes", I say "no"',
              'You say "stop", I say "go, go, go"'
            ]
}
EOF
my $json = JSON::PP->new->allow_singlequote;
my $result = $json->decode($song); # triggers "invalid character encountered while parsing..."
-*-*-*-*-*- end
```

Remark
======

FWIW, the following program works, even if there is no need to escape the
double-quote within the single-quote-delimited string:

```
# -*-*-*-*-*- begin
use JSON::PP;

my $song = <<'EOF';
{ 'title' : 'Hello Goodbye',
  'verse' : [ 'You say \"yes\", I say \"no\"',
              'You say \"stop\", I say \"go, go, go\"'
            ]
}
EOF
my $json = JSON::PP->new->allow_singlequote;
my $result = $json->decode($song);
print "first verse: ", $result->{verse}[0], "\n";
# -*-*-*-*-*- end
```

**Comment by charsbar** [comment]
You might also want to add the "loose" flag, but to be honest, if you would like to parse JSON5, then I recommend that you use the [JSON5 module](https://metacpan.org/pod/JSON5).
