### ISSUE TITLE
[doc] typos in perl-5.40.0/cpan/JSON-PP/lib/JSON/PP.pm

### ISSUE THREAD

**Issue by sobrado8086** [makamaka/JSON-PP#92]
There are a few typos in the file perl-5.40.0/cpan/JSON-PP/lib/JSON/PP.pm.  See attached diff for details.
[PP.pm.patch](https://github.com/user-attachments/files/17736060/PP.pm.patch)

**Comment by charsbar** [comment]
Thank you.
