### ISSUE TITLE
Release tag 4.17_01 to CPAN

### ISSUE THREAD

**Issue by fabzzap** [makamaka/JSON-PP#94]
Tag 4.17_01 has been created on Github.

However https://metacpan.org/pod/JSON::PP is still on version 4.16. Many bugs have been fixed in the new version.

Please make the last version available on CPAN

**Comment by charsbar** [comment]
See https://metacpan.org/release/ISHIGAKI/JSON-PP-4.17_01/view/lib/JSON/PP.pm . It has been released but it's not indexed yet as it's a developer release.

That being said, it's high time to make it stable. I'll look through the issues and ship a new version if appropriate. Thanks for the heads-up.
